# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# ranido

from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):

        self.Dashboard = Dashboard

        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(910, 610)

        base_path = os.path.join(os.path.dirname(__file__), "images")

        self.backgroundBeige = QtWidgets.QLabel(Dashboard)
        self.backgroundBeige.setGeometry(QtCore.QRect(0, 0, 910, 610))
        self.backgroundBeige.setStyleSheet("background-color: rgb(225, 221, 196);")
        self.backgroundBeige.setText("")
        self.backgroundBeige.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backgroundBeige.setObjectName("backgroundBeige")

        self.sidebarDark = QtWidgets.QLabel(Dashboard)
        self.sidebarDark.setGeometry(QtCore.QRect(0, 0, 131, 610))
        self.sidebarDark.setStyleSheet("background-color: rgb(48, 44, 36);")
        self.sidebarDark.setText("")
        self.sidebarDark.setObjectName("sidebarDark")

        self.hLine = QtWidgets.QFrame(Dashboard)
        self.hLine.setGeometry(QtCore.QRect(160, 70, 711, 1))
        self.hLine.setStyleSheet("background-color: rgb(48, 44, 36);")
        self.hLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.hLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hLine.setObjectName("hLine")

        self.dashboardLabel = QtWidgets.QLabel(Dashboard)
        self.dashboardLabel.setGeometry(QtCore.QRect(160, 40, 115, 16))
        self.dashboardLabel.setStyleSheet("font: 12pt \"Segoe MDL2 Assets\";")
        self.dashboardLabel.setObjectName("dashboardLabel")

        self.sidebarUserIcon = QtWidgets.QLabel(Dashboard)
        self.sidebarUserIcon.setGeometry(QtCore.QRect(40, 20, 61, 61))
        self.sidebarUserIcon.setText("")
        self.sidebarUserIcon.setPixmap(QtGui.QPixmap(os.path.join(base_path, "user_icon_white.png")))
        self.sidebarUserIcon.setScaledContents(True)
        self.sidebarUserIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.sidebarUserIcon.setObjectName("sidebarUserIcon")

        self.sidebarMenuSelected = QtWidgets.QLabel(Dashboard)
        self.sidebarMenuSelected.setGeometry(QtCore.QRect(0, 140, 131, 70))
        self.sidebarMenuSelected.setStyleSheet("background-color: rgb(225, 221, 196);\n""border-top-left-radius: 13px; \n""border-bottom-left-radius: 13px;")
        self.sidebarMenuSelected.setText("")
        self.sidebarMenuSelected.setObjectName("sidebarMenuSelected")

        self.sidebarDashboardLabel = QtWidgets.QLabel(Dashboard)
        self.sidebarDashboardLabel.setGeometry(QtCore.QRect(40, 187, 71, 16))
        self.sidebarDashboardLabel.setStyleSheet("font: 8pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);")
        self.sidebarDashboardLabel.setObjectName("sidebarDashboardLabel")

        self.sidebarDashboardIcon = QtWidgets.QLabel(Dashboard)
        self.sidebarDashboardIcon.setGeometry(QtCore.QRect(50, 140, 41, 51))
        self.sidebarDashboardIcon.setText("")
        self.sidebarDashboardIcon.setPixmap(QtGui.QPixmap(os.path.join(base_path, "dashboard_icon.png")))
        self.sidebarDashboardIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.sidebarDashboardIcon.setObjectName("sidebarDashboardIcon")
        
        self.sidebarFname = QtWidgets.QLabel(Dashboard)
        self.sidebarFname.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.sidebarFname.setStyleSheet("color: rgb(255, 255, 255);\n""font: 10pt \"Old Antic Bold\";")
        self.sidebarFname.setAlignment(QtCore.Qt.AlignCenter)
        self.sidebarFname.setWordWrap(True)
        self.sidebarFname.setObjectName("sidebarFname")

        self.sidebarWorkStatus = QtWidgets.QLabel(Dashboard)
        self.sidebarWorkStatus.setGeometry(QtCore.QRect(15, 100, 101, 20))
        self.sidebarWorkStatus.setStyleSheet("color: rgb(255, 255, 255);\n""font: 6pt \"MS Shell Dlg 2\";\n""\n")
        self.sidebarWorkStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.sidebarWorkStatus.setObjectName("sidebarWorkStatus")

        self.frame1 = QtWidgets.QFrame(Dashboard)
        self.frame1.setGeometry(QtCore.QRect(160, 140, 711, 88))
        self.frame1.setStyleSheet("border: 1px solid #c9c4a3; \n""background: transparent;   \n""border-top-left-radius: 10px; \n""border-bottom-left-radius: 10px;\n""border-top-right-radius: 10px; \n""border-bottom-right-radius: 10px;")
        self.frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")

        self.frame1UserIcon = QtWidgets.QLabel(self.frame1)
        self.frame1UserIcon.setGeometry(QtCore.QRect(20, 15, 61, 61))
        self.frame1UserIcon.setStyleSheet("border: transparent;")
        self.frame1UserIcon.setText("")
        self.frame1UserIcon.setPixmap(QtGui.QPixmap(os.path.join(base_path, "user_icon_dark.png")))
        self.frame1UserIcon.setScaledContents(True)
        self.frame1UserIcon.setObjectName("frame1UserIcon")

        self.frame1Fname = QtWidgets.QLabel(self.frame1)
        self.frame1Fname.setGeometry(QtCore.QRect(90, 20, 321, 16))
        self.frame1Fname.setStyleSheet("font: 11pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.frame1Fname.setObjectName("frame1Fname")

        self.frame1WorkStatus = QtWidgets.QLabel(self.frame1)
        self.frame1WorkStatus.setGeometry(QtCore.QRect(90, 38, 191, 16))
        self.frame1WorkStatus.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.frame1WorkStatus.setObjectName("frame1WorkStatus")

        self.frame1HomeAdd = QtWidgets.QLabel(self.frame1)
        self.frame1HomeAdd.setGeometry(QtCore.QRect(90, 54, 331, 16))
        self.frame1HomeAdd.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.frame1HomeAdd.setObjectName("frame1HomeAdd")

        self.fingerprintIcon = QtWidgets.QLabel(self.frame1)
        self.fingerprintIcon.setGeometry(QtCore.QRect(460, 20, 51, 51))
        self.fingerprintIcon.setStyleSheet("border: transparent;")
        self.fingerprintIcon.setText("")
        self.fingerprintIcon.setPixmap(QtGui.QPixmap(os.path.join(base_path, "fingerprint.png")))
        self.fingerprintIcon.setScaledContents(True)
        self.fingerprintIcon.setObjectName("fingerprintIcon")

        self.greenCheck = QtWidgets.QLabel(self.frame1)
        self.greenCheck.setGeometry(QtCore.QRect(500, 60, 21, 21))
        self.greenCheck.setStyleSheet("border: transparent;")
        self.greenCheck.setText("")
        self.greenCheck.setPixmap(QtGui.QPixmap(os.path.join(base_path, "recognized.png")))
        self.greenCheck.setScaledContents(True)
        self.greenCheck.setObjectName("greenCheck")

        self.frame2 = QtWidgets.QFrame(Dashboard)
        self.frame2.setGeometry(QtCore.QRect(160, 244, 711, 241))
        self.frame2.setStyleSheet("border: 1px solid #c9c4a3; \n""background: transparent;   \n""border-top-left-radius: 10px; \n""border-bottom-left-radius: 10px;\n""border-top-right-radius: 10px; \n""border-bottom-right-radius: 10px;")
        self.frame2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")

        self.personalnfo = QtWidgets.QLabel(self.frame2)
        self.personalnfo.setGeometry(QtCore.QRect(20, 13, 171, 16))
        self.personalnfo.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.personalnfo.setObjectName("personalnfo")

        self.piIdNumLabel = QtWidgets.QLabel(self.frame2)
        self.piIdNumLabel.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.piIdNumLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piIdNumLabel.setObjectName("piIdNumLabel")

        self.piIdNum = QtWidgets.QLabel(self.frame2)
        self.piIdNum.setGeometry(QtCore.QRect(20, 60, 191, 16))
        self.piIdNum.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piIdNum.setObjectName("piIdNum")
        
        self.piFnameLabel = QtWidgets.QLabel(self.frame2)
        self.piFnameLabel.setGeometry(QtCore.QRect(20, 90, 61, 16))
        self.piFnameLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piFnameLabel.setObjectName("piFnameLabel")

        self.piFname = QtWidgets.QLabel(self.frame2)
        self.piFname.setGeometry(QtCore.QRect(20, 110, 181, 16))
        self.piFname.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";""color: rgb(48, 44, 36);\n" "border: transparent;")
        self.piFname.setObjectName("piFname")

        self.piMnameLabel = QtWidgets.QLabel(self.frame2)
        self.piMnameLabel.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.piMnameLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";" "color: rgb(129, 126, 110);" "border: transparent;")
        self.piMnameLabel.setObjectName("piMnameLabel")
        self.piMname = QtWidgets.QLabel(self.frame2)
        self.piMname.setGeometry(QtCore.QRect(20, 160, 191, 16))
        self.piMname.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piMname.setObjectName("piMname")

        self.piLnameLabel = QtWidgets.QLabel(self.frame2)
        self.piLnameLabel.setGeometry(QtCore.QRect(20, 190, 61, 16))
        self.piLnameLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piLnameLabel.setObjectName("piLnameLabel")

        self.piLname = QtWidgets.QLabel(self.frame2)
        self.piLname.setGeometry(QtCore.QRect(20, 210, 181, 16))
        self.piLname.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piLname.setObjectName("piLname")

        self.piAgeLabel = QtWidgets.QLabel(self.frame2)
        self.piAgeLabel.setGeometry(QtCore.QRect(250, 40, 71, 16))
        self.piAgeLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piAgeLabel.setObjectName("piAgeLabel")

        self.piAge = QtWidgets.QLabel(self.frame2)
        self.piAge.setGeometry(QtCore.QRect(250, 60, 51, 16))
        self.piAge.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piAge.setObjectName("piAge")

        self.piBirthdateLabel = QtWidgets.QLabel(self.frame2)
        self.piBirthdateLabel.setGeometry(QtCore.QRect(250, 90, 61, 16))
        self.piBirthdateLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piBirthdateLabel.setObjectName("piBirthdateLabel")

        self.piBirthdate = QtWidgets.QLabel(self.frame2)
        self.piBirthdate.setGeometry(QtCore.QRect(250, 110, 131, 16))
        self.piBirthdate.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piBirthdate.setObjectName("piBirthdate")

        self.piGenderLabel = QtWidgets.QLabel(self.frame2)
        self.piGenderLabel.setGeometry(QtCore.QRect(250, 140, 71, 16))
        self.piGenderLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piGenderLabel.setObjectName("piGenderLabel")

        self.piGender = QtWidgets.QLabel(self.frame2)
        self.piGender.setGeometry(QtCore.QRect(250, 160, 131, 16))
        self.piGender.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piGender.setObjectName("piGender")

        self.piWorkStatusLabel = QtWidgets.QLabel(self.frame2)
        self.piWorkStatusLabel.setGeometry(QtCore.QRect(250, 190, 71, 16))
        self.piWorkStatusLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piWorkStatusLabel.setObjectName("piWorkStatusLabel")

        self.piWorkStatus = QtWidgets.QLabel(self.frame2)
        self.piWorkStatus.setGeometry(QtCore.QRect(250, 210, 131, 16))
        self.piWorkStatus.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piWorkStatus.setObjectName("piWorkStatus")

        self.piCivilStatusLabel = QtWidgets.QLabel(self.frame2)
        self.piCivilStatusLabel.setGeometry(QtCore.QRect(460, 40, 71, 16))
        self.piCivilStatusLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piCivilStatusLabel.setObjectName("piCivilStatusLabel")

        self.piCivilStatus = QtWidgets.QLabel(self.frame2)
        self.piCivilStatus.setGeometry(QtCore.QRect(460, 60, 151, 16))
        self.piCivilStatus.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piCivilStatus.setObjectName("piCivilStatus")
        
        self.piContactNumLabel = QtWidgets.QLabel(self.frame2)
        self.piContactNumLabel.setGeometry(QtCore.QRect(460, 90, 91, 16))
        self.piContactNumLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piContactNumLabel.setObjectName("piContactNumLabel")

        self.piContactNum = QtWidgets.QLabel(self.frame2)
        self.piContactNum.setGeometry(QtCore.QRect(460, 110, 131, 16))
        self.piContactNum.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piContactNum.setObjectName("piContactNum")

        self.piEmailAddLabel = QtWidgets.QLabel(self.frame2)
        self.piEmailAddLabel.setGeometry(QtCore.QRect(460, 140, 111, 16))
        self.piEmailAddLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piEmailAddLabel.setObjectName("piEmailAddLabel")

        self.piEmailAdd = QtWidgets.QLabel(self.frame2)
        self.piEmailAdd.setGeometry(QtCore.QRect(460, 160, 241, 16))
        self.piEmailAdd.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piEmailAdd.setObjectName("piEmailAdd")

        self.piHomeAddLabel = QtWidgets.QLabel(self.frame2)
        self.piHomeAddLabel.setGeometry(QtCore.QRect(460, 190, 101, 16))
        self.piHomeAddLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.piHomeAddLabel.setObjectName("piHomeAddLabel")

        self.piHomeAdd = QtWidgets.QLabel(self.frame2)
        self.piHomeAdd.setGeometry(QtCore.QRect(460, 210, 231, 16))
        self.piHomeAdd.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.piHomeAdd.setObjectName("piHomeAdd")

        self.btnLogout = QtWidgets.QPushButton(Dashboard)
        self.btnLogout.setGeometry(QtCore.QRect(0, 580, 131, 33))
        self.btnLogout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnLogout.setStyleSheet("QPushButton{ \n""background-color: #993333;\n""color: white; \n""font: 8pt \"Segoe MDL2 Assets\";\n""}\n""\n"
                                        "QPushButton:hover {\n""    background-color: #8f1f1f; \n""}")
        self.btnLogout.setObjectName("btnLogout")

        self.btnLogout.clicked.connect(self.redirect_to_login_ui)

        self.welcomeBack = QtWidgets.QLabel(Dashboard)
        self.welcomeBack.setGeometry(QtCore.QRect(160, 110, 151, 16))
        self.welcomeBack.setStyleSheet("font: 11pt \"Segoe MDL2 Assets\";")
        self.welcomeBack.setObjectName("welcomeBack")

        self.frame3 = QtWidgets.QFrame(Dashboard)
        self.frame3.setGeometry(QtCore.QRect(160, 500, 711, 88))
        self.frame3.setStyleSheet("border: 1px solid #c9c4a3; \n""background: transparent;   \n""border-top-left-radius: 10px; \n""border-bottom-left-radius: 10px;\n""border-top-right-radius: 10px; \n""border-bottom-right-radius: 10px;")
        self.frame3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")

        self.guardianInfo = QtWidgets.QLabel(self.frame3)
        self.guardianInfo.setGeometry(QtCore.QRect(20, 10, 171, 16))
        self.guardianInfo.setStyleSheet("font: 9pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.guardianInfo.setObjectName("guardianInfo")

        self.giFnameLabel = QtWidgets.QLabel(self.frame3)
        self.giFnameLabel.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.giFnameLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.giFnameLabel.setObjectName("giFnameLabel")

        self.giFname = QtWidgets.QLabel(self.frame3)
        self.giFname.setGeometry(QtCore.QRect(20, 60, 191, 16))
        self.giFname.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.giFname.setObjectName("giFname")

        self.giMnameLabel = QtWidgets.QLabel(self.frame3)
        self.giMnameLabel.setGeometry(QtCore.QRect(250, 40, 71, 16))
        self.giMnameLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.giMnameLabel.setObjectName("giMnameLabel")

        self.giMname = QtWidgets.QLabel(self.frame3)
        self.giMname.setGeometry(QtCore.QRect(250, 60, 191, 16))
        self.giMname.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.giMname.setObjectName("giMname")

        self.giLnameLabel = QtWidgets.QLabel(self.frame3)
        self.giLnameLabel.setGeometry(QtCore.QRect(460, 40, 71, 16))
        self.giLnameLabel.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(129, 126, 110);\n""border: transparent;\n")
        self.giLnameLabel.setObjectName("giLnameLabel")

        self.giLname = QtWidgets.QLabel(self.frame3)
        self.giLname.setGeometry(QtCore.QRect(460, 60, 221, 16))
        self.giLname.setStyleSheet("font: 7pt \"Segoe MDL2 Assets\";\n""color: rgb(48, 44, 36);\n""border: transparent;\n")
        self.giLname.setObjectName("giLname")

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Form"))
        self.dashboardLabel.setText(_translate("Dashboard", "DASHBOARD"))
        self.sidebarDashboardLabel.setText(_translate("Dashboard", "Dashboard"))
        self.sidebarFname.setText(_translate("Dashboard", "John Doe"))
        self.sidebarWorkStatus.setText(_translate("Dashboard", "Student"))
        self.frame1Fname.setText(_translate("Dashboard", "John Doe"))
        self.frame1WorkStatus.setText(_translate("Dashboard", "Student"))
        self.frame1HomeAdd.setText(_translate("Dashboard", "Pajac, Lapu-Lapu City"))
        self.personalnfo.setText(_translate("Dashboard", "Personal Information"))
        self.piIdNumLabel.setText(_translate("Dashboard", "ID Number"))
        self.piIdNum.setText(_translate("Dashboard", "1334856"))
        self.piFnameLabel.setText(_translate("Dashboard", "First Name"))
        self.piFname.setText(_translate("Dashboard", "John"))
        self.piMnameLabel.setText(_translate("Dashboard", "Middle Name"))
        self.piMname.setText(_translate("Dashboard", "N/A"))
        self.piLnameLabel.setText(_translate("Dashboard", "Last Name"))
        self.piLname.setText(_translate("Dashboard", "Doe"))
        self.piAgeLabel.setText(_translate("Dashboard", "Age"))
        self.piAge.setText(_translate("Dashboard", "21"))
        self.piBirthdateLabel.setText(_translate("Dashboard", "Birthdate"))
        self.piBirthdate.setText(_translate("Dashboard", "12-25-2002"))
        self.piGenderLabel.setText(_translate("Dashboard", "Gender"))
        self.piGender.setText(_translate("Dashboard", "Male"))
        self.piWorkStatusLabel.setText(_translate("Dashboard", "Work Status"))
        self.piWorkStatus.setText(_translate("Dashboard", "Student"))
        self.piCivilStatusLabel.setText(_translate("Dashboard", "Civil Status"))
        self.piCivilStatus.setText(_translate("Dashboard", "Single"))
        self.piContactNumLabel.setText(_translate("Dashboard", "Contact Number"))
        self.piContactNum.setText(_translate("Dashboard", "09101883946"))
        self.piEmailAddLabel.setText(_translate("Dashboard", "Email Address"))
        self.piEmailAdd.setText(_translate("Dashboard", "johndoe@gmail.com"))
        self.piHomeAddLabel.setText(_translate("Dashboard", "Home Address"))
        self.piHomeAdd.setText(_translate("Dashboard", "Pajac, Lapu-Lapu City"))
        self.btnLogout.setText(_translate("Dashboard", "Logout"))
        self.welcomeBack.setText(_translate("Dashboard", "Welcome Back!"))
        self.guardianInfo.setText(_translate("Dashboard", "Guardian Information"))
        self.giFnameLabel.setText(_translate("Dashboard", "First Name"))
        self.giFname.setText(_translate("Dashboard", "Henry"))
        self.giMnameLabel.setText(_translate("Dashboard", "Middle Name"))
        self.giMname.setText(_translate("Dashboard", "Fritz"))
        self.giLnameLabel.setText(_translate("Dashboard", "Last Name"))
        self.giLname.setText(_translate("Dashboard", "Doe"))

    def redirect_to_login_ui(self):
        from login_page import Ui_Form 
        self.Dashboard.hide()
        self.loginWindow = QtWidgets.QWidget()
        self.ui = Ui_Form() 
        self.ui.setupUi(self.loginWindow) 
        self.loginWindow.show()  

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dashboard = QtWidgets.QWidget()
    ui = Ui_Dashboard()
    ui.setupUi(Dashboard)
    Dashboard.setWindowFlags(Dashboard.windowFlags() & ~QtCore.Qt.WindowMaximizeButtonHint)
    Dashboard.show()
    sys.exit(app.exec_())