# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Downloads\biomet_files\confirm_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#flores


import os
from PyQt5.QtWidgets import QApplication, QLabel, QWidget, QPushButton
from PyQt5.QtGui import QMovie, QFont
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QTimer


class Ui_Reg_Scan_Form(object):
    def setupUi(self, Form):
        self.Form = Form 

        Form.setObjectName("Form")
        Form.resize(910, 610)

        base_path = os.path.join(os.path.dirname(__file__), "images")
        ctu_bg = os.path.join(base_path, "ctu-bg.jpg").replace("\\", "/")
        
        self.ctuBG = QtWidgets.QLabel(Form)
        self.ctuBG.setGeometry(QtCore.QRect(0, 0, 910, 610))
        self.ctuBG.setStyleSheet(
                                "background-image: url(" + ctu_bg + ");"
                                "background-blend-mode: overlay;"
                                "background-color: rgba(218, 212, 181, 0.4);"
                            )
        self.ctuBG.setText("")
        self.ctuBG.setObjectName("ctuBG")
        
        self.seethroughBlackBG = QtWidgets.QLabel(Form)
        self.seethroughBlackBG.setGeometry(QtCore.QRect(150, 90, 631, 411))
        self.seethroughBlackBG.setStyleSheet(
                                            "background-color: rgb(19, 19, 19);"
                                            "border-radius: 15px;"
                                        )
        self.seethroughBlackBG.setText("")
        self.seethroughBlackBG.setObjectName("seethroughBlackBG")

        self.peachBG = QtWidgets.QLabel(Form)
        self.peachBG.setGeometry(QtCore.QRect(0, 0, 910, 610))
        self.peachBG.setStyleSheet("background-color: rgba(218, 212, 181, 130);")
        self.peachBG.setText("")
        self.peachBG.setObjectName("peachBG")

        self.placeYourFingerLabel = QtWidgets.QLabel(Form)
        self.placeYourFingerLabel.setGeometry(QtCore.QRect(350, 345, 241, 18))

        base_path = os.path.join(os.path.dirname(__file__), "images")
        scan_gif = os.path.join(base_path, "fingerprint-gif.gif").replace("\\", "/")

        self.fingerprint_gif = QtWidgets.QLabel(Form)
        self.fingerprint_gif.setGeometry(QtCore.QRect(310, 120, 311, 241)) 
        self.fingerprint_gif.setText("")
        self.fingerprint_gif.setObjectName("fingerprint_gif")

        movie = QMovie(scan_gif)
        self.fingerprint_gif.setMovie(movie)
        movie.setScaledSize(self.fingerprint_gif.size())
        movie.setSpeed(43)
        movie.start()

        font = QFont() 
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)

        self.placeYourFingerLabel.setFont(font)
        self.placeYourFingerLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.placeYourFingerLabel.setObjectName("placeYourFingerLabel")
        self.placeYourFingerLabel.setText("Place your finger on the scanner")

        # ang way nga ako gibuhat kay bali wa nay button mo trigger nga magsugod ug scan
        # diritso na ug scan if mo appear ang kani nga window
        
        QTimer.singleShot(2300, self.changeText) # gipang timer nalang nako ari, idk if sapat ba ni to fully scan sa fingerprint
        QTimer.singleShot(7100, self.changeGif)
        
        self.ctuBG.raise_()
        self.peachBG.raise_()
        self.seethroughBlackBG.raise_()
        self.fingerprint_gif.raise_()
        self.placeYourFingerLabel.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Scan", "Scan"))
        self.placeYourFingerLabel.setText(_translate("Form", "Place your finger on the scanner"))

    def changeText(self):
        self.placeYourFingerLabel.setText("                   Scanning...")

    def changeGif(self):
        base_path = os.path.join(os.path.dirname(__file__), "images")
        check_gif = os.path.join(base_path, "checkscan.gif").replace("\\", "/")

        new_movie = QMovie(check_gif)
        self.placeYourFingerLabel.setText("      Success! Fingerprint added.")
        self.fingerprint_gif.setMovie(new_movie)
        self.fingerprint_gif.setGeometry(QtCore.QRect(380, 150, 180, 180)) 
        new_movie.setScaledSize(self.fingerprint_gif.size())
        new_movie.start()

        self.backButton = QPushButton("Back", self.fingerprint_gif.parent()) 
        self.backButton.setGeometry(QtCore.QRect(420, 390, 100, 40))  
        self.backButton.setStyleSheet(
                "background-color: rgb(153, 51, 51);"
                "color: white;"
                "font-weight: bold;"
                "border: none;"
                "border-radius: 5px;"
            )
        self.backButton.clicked.connect(self.onBackButtonClick)
        self.backButton.show() 

    def onBackButtonClick(self):  
        self.Form.hide()
        
        # parent = self.Form.parentWidget() 
        # if parent is not None:
        #     parent.show()  
        # self.Form.close() 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Reg_Scan_Form()
    ui.setupUi(Form)
    Form.setWindowFlags(Form.windowFlags() & ~QtCore.Qt.WindowMaximizeButtonHint)
    Form.show()
    sys.exit(app.exec_())


    # app = QtWidgets.QApplication(sys.argv)

    # previous_window = QWidget()
    # previous_window.setWindowTitle("Previous Window")
    # previous_window.resize(910, 610)

    # current_window = QWidget(parent=previous_window)
    # ui = Ui_Reg_Scan_Form()
    # ui.setupUi(current_window)
    
    # previous_window.show()

    # sys.exit(app.exec_())