# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, Form):
        self.Form = Form
        Form.setObjectName("Form")
        Form.resize(910, 607)
        self.ctuBG = QtWidgets.QLabel(Form)
        self.ctuBG.setGeometry(QtCore.QRect(0, 0, 910, 610))
        self.ctuBG.setStyleSheet("background-image: url(D:/Downloads/biomet_files/images/ctu-bg.jpg);\n"
        "background-blend-mode: overlay;\n"
        "background-color: rgba(218, 212, 181, 0.4);\n"
        "")
        self.ctuBG.setText("")
        self.ctuBG.setObjectName("ctuBG")


        self.seethroughBlackBG = QtWidgets.QLabel(Form)
        self.seethroughBlackBG.setGeometry(QtCore.QRect(41, 30, 831, 551))
        self.seethroughBlackBG.setStyleSheet("\n"
        "background-color: rgb(36, 36, 36,210);\n"
        "border-radius: 15px;\n"
        "")
        self.seethroughBlackBG.setText("")
        self.seethroughBlackBG.setObjectName("seethroughBlackBG")


        self.idnumInput = QtWidgets.QLineEdit(Form)
        self.idnumInput.setGeometry(QtCore.QRect(80, 150, 221, 35))
        self.idnumInput.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.idnumInput.setInputMask("")
        self.idnumInput.setText("")
        self.idnumInput.setObjectName("idnumInput")


        self.fnameInput = QtWidgets.QLineEdit(Form)
        self.fnameInput.setGeometry(QtCore.QRect(80, 210, 221, 35))
        self.fnameInput.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.fnameInput.setText("")
        self.fnameInput.setObjectName("fnameInput")


        self.ctuBG_2 = QtWidgets.QLabel(Form)
        self.ctuBG_2.setGeometry(QtCore.QRect(0, 0, 910, 610))
        self.ctuBG_2.setStyleSheet("background-color: rgb(218, 212, 181,130);")
        self.ctuBG_2.setText("")
        self.ctuBG_2.setObjectName("ctuBG_2")


        self.regFormBlackBG = QtWidgets.QLabel(Form)
        self.regFormBlackBG.setGeometry(QtCore.QRect(41, 60, 830, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.regFormBlackBG.setFont(font)
        self.regFormBlackBG.setStyleSheet("background-color: rgb(36, 36, 36);\n"
        "color: rgb(255, 255, 255);")
        self.regFormBlackBG.setTextFormat(QtCore.Qt.AutoText)
        self.regFormBlackBG.setScaledContents(False)
        self.regFormBlackBG.setWordWrap(False)
        self.regFormBlackBG.setIndent(330)
        self.regFormBlackBG.setObjectName("regFormBlackBG")


        self.mnameInput = QtWidgets.QLineEdit(Form)
        self.mnameInput.setGeometry(QtCore.QRect(350, 210, 221, 35))
        self.mnameInput.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.mnameInput.setText("")
        self.mnameInput.setObjectName("mnameInput")


        self.lnameInput = QtWidgets.QLineEdit(Form)
        self.lnameInput.setGeometry(QtCore.QRect(610, 210, 221, 35))
        self.lnameInput.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.lnameInput.setText("")
        self.lnameInput.setObjectName("lnameInput")


        self.genderDropdown = QtWidgets.QComboBox(Form)
        self.genderDropdown.setGeometry(QtCore.QRect(80, 330, 221, 35))
        self.genderDropdown.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.genderDropdown.setObjectName("genderDropdown")
        self.genderDropdown.addItem("Gender")
        self.genderDropdown.addItems(["Female", "Male", "Other"])
        # Disable the placeholder - para di sya ma pick ni user
        self.genderDropdown.setItemData(0, 0, QtCore.Qt.UserRole - 1)


        self.civilStatus = QtWidgets.QComboBox(Form)
        self.civilStatus.setGeometry(QtCore.QRect(350, 330, 221, 35))
        self.civilStatus.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.civilStatus.setFrame(True)
        self.civilStatus.setObjectName("civilStatus")
        self.civilStatus.addItem("Civil Status")
        self.civilStatus.addItems([ "Single","Married", "Divorced"])
        # Disable the placeholder - para di sya ma pick ni user
        self.civilStatus.setItemData(0, 0, QtCore.Qt.UserRole - 1)


        self.workStatus = QtWidgets.QComboBox(Form)
        self.workStatus.setGeometry(QtCore.QRect(610, 330, 221, 35))
        self.workStatus.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.workStatus.setFrame(True)
        self.workStatus.setObjectName("workStatus")
        self.workStatus.addItem("Work Status")
        self.workStatus.addItems(["Employed", "Unemployed", "Student"])
        # Disable the placeholder - para di sya ma pick ni user
        self.workStatus.setItemData(0, 0, QtCore.Qt.UserRole - 1)


        self.contactInput = QtWidgets.QLineEdit(Form)
        self.contactInput.setGeometry(QtCore.QRect(80, 270, 221, 35))
        self.contactInput.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.contactInput.setText("")
        self.contactInput.setObjectName("contactInput")


        self.emailInput = QtWidgets.QLineEdit(Form)
        self.emailInput.setGeometry(QtCore.QRect(610, 150, 221, 35))
        self.emailInput.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.emailInput.setText("")
        self.emailInput.setObjectName("emailInput")


        self.addressInput = QtWidgets.QLineEdit(Form)
        self.addressInput.setGeometry(QtCore.QRect(350, 150, 221, 35))
        self.addressInput.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.addressInput.setText("")
        self.addressInput.setObjectName("addressInput")


        self.GuardianFname = QtWidgets.QLineEdit(Form)
        self.GuardianFname.setGeometry(QtCore.QRect(350, 410, 221, 35))
        self.GuardianFname.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.GuardianFname.setText("")
        self.GuardianFname.setObjectName("GuardianFname")


        self.GuardianMname = QtWidgets.QLineEdit(Form)
        self.GuardianMname.setGeometry(QtCore.QRect(610, 410, 221, 35))
        self.GuardianMname.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.GuardianMname.setText("")
        self.GuardianMname.setObjectName("GuardianMname")


        self.fingerprintBtn = QtWidgets.QPushButton(Form)
        self.fingerprintBtn.setGeometry(QtCore.QRect(670, 470, 101, 91))
        self.fingerprintBtn.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.fingerprintBtn.setText("")
        self.fingerprintBtn.setObjectName("fingerprintBtn")

        self.fingerprintBtn.clicked.connect(self.openRegScanWindow)


        self.fingerprintImage = QtWidgets.QLabel(Form)
        self.fingerprintImage.setGeometry(QtCore.QRect(700, 480, 41, 41))
        self.fingerprintImage.setStyleSheet("image: url(D:/Downloads/biomet_files/images/fingerprint.png);")
        self.fingerprintImage.setText("")
        self.fingerprintImage.setObjectName("fingerprintImage")


        self.fingerprintLabel = QtWidgets.QLabel(Form)
        self.fingerprintLabel.setGeometry(QtCore.QRect(690, 530, 61, 16))
        self.fingerprintLabel.setStyleSheet("color: rgb(93, 93, 93);")
        self.fingerprintLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fingerprintLabel.setObjectName("fingerprintLabel")


        self.regSaveBtn = QtWidgets.QPushButton(Form)
        self.regSaveBtn.setGeometry(QtCore.QRect(340, 490, 113, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.regSaveBtn.setFont(font)
        self.regSaveBtn.setStyleSheet("background-color: rgb(153, 51, 51);\n"
        "border: 0; \n"
        "border-radius: 4px;\n"
        "color: rgb(255, 255, 255);")
        self.regSaveBtn.setObjectName("regSaveBtn")
        self.regSaveBtn.clicked.connect(self.openConfirmationWindow)


        self.regCancelBtn = QtWidgets.QPushButton(Form)
        self.regCancelBtn.setGeometry(QtCore.QRect(470, 490, 113, 35))
        self.regCancelBtn.setStyleSheet("background-color: rgb(211, 211, 211);\n"
        "border: 0; \n"
        "border-radius: 4px;\n"
        "")
        self.regCancelBtn.setObjectName("regCancelBtn")
        self.regCancelBtn.clicked.connect(self.redirect_to_login_ui)


        self.Birthdate = QtWidgets.QDateEdit(Form)
        self.Birthdate.setEnabled(True)
        self.Birthdate.setGeometry(QtCore.QRect(610, 270, 221, 35))
        self.Birthdate.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.Birthdate.setAccelerated(False)
        self.Birthdate.setCalendarPopup(True)
        self.Birthdate.setObjectName("Birthdate")


        self.GuardianLname = QtWidgets.QLineEdit(Form)
        self.GuardianLname.setGeometry(QtCore.QRect(80, 410, 221, 35))
        self.GuardianLname.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.GuardianLname.setObjectName("GuardianLname")


        self.ageinput = QtWidgets.QLineEdit(Form)
        self.ageinput.setGeometry(QtCore.QRect(350, 270, 221, 35))
        self.ageinput.setStyleSheet("padding: 5px;\n"
        "border: 0;\n"
        "border-radius: 7px;\n"
        "background-color: rgb(218, 212, 181);")
        self.ageinput.setObjectName("ageinput")


        self.StudentInfoLabel = QtWidgets.QLabel(Form)
        self.StudentInfoLabel.setGeometry(QtCore.QRect(80, 100, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.StudentInfoLabel.setFont(font)
        self.StudentInfoLabel.setStyleSheet("\n"
        "color: rgb(255, 255, 255);")
        self.StudentInfoLabel.setTextFormat(QtCore.Qt.AutoText)
        self.StudentInfoLabel.setScaledContents(False)
        self.StudentInfoLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.StudentInfoLabel.setWordWrap(False)
        self.StudentInfoLabel.setIndent(330)
        self.StudentInfoLabel.setObjectName("StudentInfoLabel")


        self.GuardianInfoLabel = QtWidgets.QLabel(Form)
        self.GuardianInfoLabel.setGeometry(QtCore.QRect(80, 360, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.GuardianInfoLabel.setFont(font)
        self.GuardianInfoLabel.setStyleSheet("\n"
        "color: rgb(255, 255, 255);")
        self.GuardianInfoLabel.setTextFormat(QtCore.Qt.AutoText)
        self.GuardianInfoLabel.setScaledContents(False)
        self.GuardianInfoLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.GuardianInfoLabel.setWordWrap(False)
        self.GuardianInfoLabel.setIndent(330)
        self.GuardianInfoLabel.setObjectName("GuardianInfoLabel")


        self.ctuBG.raise_()
        self.ctuBG_2.raise_()
        self.seethroughBlackBG.raise_()
        self.idnumInput.raise_()
        self.fnameInput.raise_()
        self.regFormBlackBG.raise_()
        self.mnameInput.raise_()
        self.lnameInput.raise_()
        self.genderDropdown.raise_()
        self.civilStatus.raise_()
        self.workStatus.raise_()
        self.contactInput.raise_()
        self.emailInput.raise_()
        self.addressInput.raise_()
        self.GuardianFname.raise_()
        self.GuardianMname.raise_()
        self.fingerprintBtn.raise_()
        self.fingerprintImage.raise_()
        self.fingerprintLabel.raise_()
        self.regSaveBtn.raise_()
        self.regCancelBtn.raise_()
        self.Birthdate.raise_()
        self.GuardianLname.raise_()
        self.ageinput.raise_()
        self.StudentInfoLabel.raise_()
        self.GuardianInfoLabel.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.idnumInput.setPlaceholderText(_translate("Form", "ID Number"))
        self.fnameInput.setPlaceholderText(_translate("Form", "First Name"))
        self.regFormBlackBG.setText(_translate("Form", "REGISTRATION FORM"))
        self.mnameInput.setPlaceholderText(_translate("Form", "Middle Name"))
        self.lnameInput.setPlaceholderText(_translate("Form", "Last Name"))
        self.contactInput.setPlaceholderText(_translate("Form", "Contact Number"))
        self.emailInput.setPlaceholderText(_translate("Form", "Email Address"))
        self.addressInput.setPlaceholderText(_translate("Form", "Home Address"))
        self.GuardianFname.setPlaceholderText(_translate("Form", "Guardian\'s Middle Name"))
        self.GuardianMname.setPlaceholderText(_translate("Form", "Guardian\'s Last Name"))
        self.fingerprintLabel.setText(_translate("Form", "Fingerprint"))
        self.regSaveBtn.setText(_translate("Form", "Next"))
        self.regCancelBtn.setText(_translate("Form", "Cancel"))
        self.GuardianLname.setPlaceholderText(_translate("Form", "Guardian\'s First Name"))
        self.ageinput.setPlaceholderText(_translate("Form", "Age"))
        self.StudentInfoLabel.setText(_translate("Form", "Student Information"))
        self.GuardianInfoLabel.setText(_translate("Form", "Guardian Information"))


    def openConfirmationWindow(self):
        from confirm_registration import Ui_Form
        self.Form.hide()
        self.confirmWindow = QtWidgets.QWidget()
        self.ui = Ui_Form()  
        self.ui.setupUi(self.confirmWindow) 
        self.confirmWindow.show()

    def redirect_to_login_ui(self):
        from login_page import Ui_Form 
        self.Form.hide()
        self.loginWindow = QtWidgets.QWidget()
        self.ui = Ui_Form() 
        self.ui.setupUi(self.loginWindow) 
        self.loginWindow.show()  

    def openRegScanWindow(self):
        from reg_scan_page import Ui_Reg_Scan_Form 
        self.regScanWindow = QtWidgets.QWidget()
        self.ui = Ui_Reg_Scan_Form()  
        self.ui.setupUi(self.regScanWindow) 
        self.regScanWindow.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_RegisterForm()
    ui.setupUi(Form)
    Form.setWindowFlags(Form.windowFlags() & ~QtCore.Qt.WindowMaximizeButtonHint)
    Form.show()
    sys.exit(app.exec_())
