# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Downloads\biomet_files\confirm_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# flores

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SuccessRegForm(object):

    def setupUi(self, Form):

        Form.setObjectName("Form")
        self.window = Form

        Form.resize(391, 322)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(162, 40, 65, 65))
        self.label.setStyleSheet("""
                                background-color: rgb(0, 170, 0);
                                border-radius: 32px;
                            """)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(173, 52, 42, 42))
        self.label_2.setStyleSheet("image: url(D:/Downloads/biomet_files/images/checkpng.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 80, 291, 191))
        self.label_3.setStyleSheet("""
                                    background-color: rgb(255, 244, 230);
                                    border-radius: 10px;
                                """)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(158, 132, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(140, 162, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(144, 220, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("""
                                    background-color: rgb(153, 51, 51);
                                    border: 0;
                                    border-radius: 4px;
                                    color: rgb(255, 255, 255);
                                """)
        self.pushButton.setObjectName("pushButton")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()

        self.pushButton.clicked.connect(self.redirect_to_login_ui)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Success!"))
        self.label_5.setText(_translate("Form", "Registration Complete. "))
        self.pushButton.setText(_translate("Form", "Back to Login"))

    def redirect_to_login_ui(self):
        from login_page import Ui_Form
        self.window.hide()
        self.loginWindow = QtWidgets.QWidget()
        self.ui = Ui_Form() 
        self.ui.setupUi(self.loginWindow)  
        self.loginWindow.show() 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_SuccessRegForm()
    ui.setupUi(Form)
    Form.setWindowFlags(Form.windowFlags() & ~QtCore.Qt.WindowMaximizeButtonHint)
    Form.show()
    sys.exit(app.exec_())
