# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Downloads\biomet_files\unrecognized_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Unrecognized_formIMdGcJ.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from register_page import Ui_RegisterForm
from login_page import Ui_Form

class Login(QWidget):
    def __init__(self,parent = None):
        super().__init__(parent)
        self.ui = Ui_Form()
        self.ui.setupUi(self)
class Register(QWidget):
    def __init__(self,parent = None):
        super().__init__(parent)
        self.ui = Ui_RegisterForm()
        self.ui.setupUi(self)



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(375, 192)
        self.horizontalLayout = QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u" background-color: #F5F5DC;\n"
"border: 2px solid #FFD700;\n"
"border-radius: 5px;")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(70, 40, 211, 31))
        self.label.setStyleSheet(u"color: black;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"background-color: transparent;")
        self.pushButton = QPushButton(self.frame)
        self.pushButton.clicked.connect(self.on_log)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(80, 100, 75, 23))
        self.pushButton.setStyleSheet(u"QPushButton {\n"
"                background-color: #800000;  /* Maroon background */\n"
"                color: white;  /* White text */\n"
"                font-weight: bold;  /* Bold text */\n"
"                border: 2px solid #FFD700;  /* Yellow border */\n"
"                border-radius: 10px;  /* Rounded corners */\n"
"                font-size: 14px;  /* Font size */\n"
"                box-shadow: 2px 2px 8px #333333;  /* Shadow effect */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #FFD700;  /* Yellow on hover */\n"
"                color: black;  /* Black text on hover */\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #FF4500;  /* Bright red when clicked */\n"
"                color: white;  /* White text when clicked */\n"
"            }")
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.clicked.connect(self.on_login_clicked)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(190, 100, 75, 23))
        self.pushButton_2.setStyleSheet(u"QPushButton {\n"
"                background-color: #800000;  /* Maroon background */\n"
"                color: white;  /* White text */\n"
"                font-weight: bold;  /* Bold text */\n"
"                border: 2px solid #FFD700;  /* Yellow border */\n"
"                border-radius: 10px;  /* Rounded corners */\n"
"                font-size: 14px;  /* Font size */\n"
"                box-shadow: 2px 2px 8px #333333;  /* Shadow effect */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #FFD700;  /* Yellow on hover */\n"
"                color: black;  /* Black text on hover */\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #FF4500;  /* Bright red when clicked */\n"
"                color: white;  /* White text when clicked */\n"
"            }")

        self.horizontalLayout.addWidget(self.frame)


        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Unrecognized Login Credentials", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Login", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Register", None))
    # retranslateUi

    def on_log(self):
        self.frame.parentWidget().close()
        self.login = Login()
        self.login.show()
    def on_login_clicked(self):
        self.frame.parentWidget().close()
        self.register = Register()
        self.register.show()
        print("Login button clicked")

if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())





# class Ui_Form(object):
#         def setupUi(self, Form):
#                 Form.setObjectName("Form")

#                 self.Form = Form 

#                 Form.resize(910, 610)
#                 self.ctuBG = QtWidgets.QLabel(Form)
#                 self.ctuBG.setGeometry(QtCore.QRect(0, 0, 910, 610))
#                 self.ctuBG.setStyleSheet("background-image: url(D:/Downloads/biomet_files/images/ctu-bg.jpg);\n"
#         "background-blend-mode: overlay;\n"
#         "background-color: rgba(218, 212, 181, 0.4);\n"
#         "")
#                 self.ctuBG.setText("")
#                 self.ctuBG.setObjectName("ctuBG")
#                 self.seethroughBlackBG = QtWidgets.QLabel(Form)
#                 self.seethroughBlackBG.setGeometry(QtCore.QRect(250, 160, 431, 311))
#                 self.seethroughBlackBG.setStyleSheet("background-color: rgb(0, 0, 0,190);\n"
#         "border-radius: 15px;\n"
#         "")
#                 self.seethroughBlackBG.setText("")
#                 self.seethroughBlackBG.setObjectName("seethroughBlackBG")
#                 self.ctuBG_2 = QtWidgets.QLabel(Form)
#                 self.ctuBG_2.setGeometry(QtCore.QRect(0, 0, 910, 610))
#                 self.ctuBG_2.setStyleSheet("background-color: rgb(218, 212, 181,130);")
#                 self.ctuBG_2.setText("")
#                 self.ctuBG_2.setObjectName("ctuBG_2")
#                 self.unrecognizedLabel = QtWidgets.QLabel(Form)
#                 self.unrecognizedLabel.setGeometry(QtCore.QRect(340, 240, 341, 41))
#                 font = QtGui.QFont()
#                 font.setPointSize(12)
#                 font.setBold(True)
#                 font.setWeight(75)
#                 self.unrecognizedLabel.setFont(font)
#                 self.unrecognizedLabel.setStyleSheet("color: rgb(255, 255, 0);")
#                 self.unrecognizedLabel.setScaledContents(False)
#                 self.unrecognizedLabel.setWordWrap(False)
#                 self.unrecognizedLabel.setObjectName("unrecognizedLabel")
#                 self.alertPng = QtWidgets.QLabel(Form)
#                 self.alertPng.setGeometry(QtCore.QRect(410, 120, 111, 91))
#                 self.alertPng.setStyleSheet("image: url(D:/Downloads/biomet_files/images/alert.png);")
#                 self.alertPng.setText("")
#                 self.alertPng.setObjectName("alertPng")
#                 self.loginBtn = QtWidgets.QPushButton(Form)
#                 self.loginBtn.setGeometry(QtCore.QRect(410, 340, 120, 35))
#                 self.loginBtn.setStyleSheet("background-color: rgb(153, 51, 51);\n"
#         "border: 0;\n"
#         "border-radius: 4px;\n"
#         "color: rgb(255, 255, 255);")
#                 self.loginBtn.setObjectName("loginBtn")

#                 self.loginBtn.clicked.connect(self.redirect_to_login_ui)

#                 self.registerBtn = QtWidgets.QPushButton(Form)
#                 self.registerBtn.setGeometry(QtCore.QRect(492, 390, 111, 35))
#                 font = QtGui.QFont()
#                 font.setBold(True)
#                 font.setUnderline(True)
#                 font.setWeight(75)
#                 self.registerBtn.setFont(font)
#                 self.registerBtn.setStyleSheet("background-color: transparent;\n"
#         "color: rgb(255, 255, 255);\n"
#         "text-decoration: underline;")
#                 self.registerBtn.setObjectName("registerBtn")

#                 self.registerBtn.clicked.connect(self.redirect_to_register_ui)

#                 self.label = QtWidgets.QLabel(Form)
#                 self.label.setGeometry(QtCore.QRect(338, 400, 161, 16))
#                 font = QtGui.QFont()
#                 font.setBold(False)
#                 font.setWeight(50)
#                 self.label.setFont(font)
#                 self.label.setStyleSheet("color: rgb(255, 255, 255);")
#                 self.label.setObjectName("label")
#                 self.ctuBG.raise_()
#                 self.ctuBG_2.raise_()
#                 self.seethroughBlackBG.raise_()
#                 self.unrecognizedLabel.raise_()
#                 self.alertPng.raise_()
#                 self.loginBtn.raise_()
#                 self.registerBtn.raise_()
#                 self.label.raise_()

#                 self.retranslateUi(Form)
#                 QtCore.QMetaObject.connectSlotsByName(Form)

#         def retranslateUi(self, Form):
#                 _translate = QtCore.QCoreApplication.translate
#                 Form.setWindowTitle(_translate("Form", "Unrecognized"))
#                 self.unrecognizedLabel.setText(_translate("Form", "Unrecognized Fingerprint"))
#                 self.loginBtn.setText(_translate("Form", "Back to Login"))
#                 self.registerBtn.setText(_translate("Form", "Register here"))
#                 self.label.setText(_translate("Form", "Don\'t have an account yet?"))

#         def redirect_to_login_ui(self):
#                 from login_page import Ui_Form 
#                 self.Form.hide()
#                 self.loginWindow = QtWidgets.QWidget()
#                 self.ui = Ui_Form()
#                 self.ui.setupUi(self.loginWindow) 
#                 self.loginWindow.show()

#         def redirect_to_register_ui(self):
#                 from register_page import Ui_RegisterForm 
#                 self.Form.hide()
#                 self.regWindow = QtWidgets.QWidget()
#                 self.ui = Ui_RegisterForm()
#                 self.ui.setupUi(self.regWindow) 
#                 self.regWindow.show()

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.setWindowFlags(Form.windowFlags() & ~QtCore.Qt.WindowMaximizeButtonHint)
#     Form.show()
#     sys.exit(app.exec_())
